'map-data':
  bikeracks:
    fields:
      - Latitude
      - Longitude
  bluelights:
    fields:
      - Name
      - Latitude
      - Longitude
  buildings:
    fields:
      - Name
      - Category
      - ImageURL
      - Address
      - Latitude
      - Longitude
      - Notes
      - AKA
  campustocampus:
    fields:
      - Name
      - Latitude
      - Longitude
  carshare:
    fields:
      - Name
      - Latitude
      - Longitude
  diaperchangingstations:
    fields:
      - Latitude
      - Longitude
  infobooths:
    fields:
      - Name
      - Latitude
      - Longitude
  lactationrooms:
    fields:
      - Name
      - Latitude
      - Longitude
  parking:
    fields:
      - Name
      - Address
      - Latitude
      - Longitude
      - Notes
  parkmobile:
    fields:
      - ID
      - Name
      - Latitude
      - Longitude
      - Address
      - Notes
  virtualtour:
    fields:
      - ID
      - Name
      - Description
      - PanDegrees
      - TiltDegrees
      - Latitude
      - Longitude
      - View
'TCAT-data':
  'route-schedules':
    fields:
      - Route
      - RouteInstance
      - Day
      - Direction
      - Stop
      - Time
  'stop-schedules':
    fields:
      - Stop
      - Route
      - Day
      - Direction
      - Time
  'stop-locations':
    fields:
      - Name
      - Latitude
      - Longitude
'events-data':
  data:
    fields:
      - Date
      - Latitude
      - Description
      - PubDate
      - Title
      - Content
      - Link
      - GUID
      - Longitude